trigger: 
- main
pool: Agent-steps-Jobs-Stages
name: Jobs-pipeline
jobs:
- job: terraformbasickarna 
  displayName: terraform(init/validate/plan)
  steps: 
  - task: TerraformInstaller@1
    displayName: terraform install
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTask@5
    displayName: terraform init
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'steps-Jobs-Stages-Service'
      backendAzureRmOverrideSubscriptionID: '4a8937a7-b294-4a1f-8d31-79bbb1a4c17f'
      backendAzureRmResourceGroupName: 'jobs-rg'
      backendAzureRmStorageAccountName: 'jobs987654321'
      backendAzureRmContainerName: 'jobs-c'
      backendAzureRmKey: 'terraform.tfstate'
  - task: TerraformTask@5
    displayName: terraform validate
    inputs:
      provider: 'azurerm'	
      command: 'validate'
  - task: TerraformTask@5
    displayName: terraform plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'steps-Jobs-Stages-Service'
- job: validationkarna
  displayName: maunal validation
  dependsOn: terraformbasickarna 
  pool: server
  steps: 
  - task: ManualValidation@1
    inputs:
      notifyUsers: 'pradum@azuredevopsterraformdockerg.onmicrosoft.com'
      approvers: 'pradum@azuredevopsterraformdockerg.onmicrosoft.com'
- job: applykarna
  displayName: terraform init/apply
  dependsOn: validationkarna
  steps:
  - task: TerraformTask@5
    displayName: terraform init
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'steps-Jobs-Stages-Service'
      backendAzureRmOverrideSubscriptionID: '4a8937a7-b294-4a1f-8d31-79bbb1a4c17f'
      backendAzureRmResourceGroupName: 'jobs-rg'
      backendAzureRmStorageAccountName: 'jobs987654321'
      backendAzureRmContainerName: 'jobs-c'
      backendAzureRmKey: 'terraform.tfstate'
  - task: TerraformTask@5
    displayName: terraform apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'steps-Jobs-Stages-Service'
